product.service.url: http://localhost:8091/product/
user.service.url: http//localhost:8092/user/

spring:
  datasource:
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.1.95:9003/reactive_microservice
  jpa:
    hibernate:
      ddl-auto: validate